#!/usr/bin/env bash

# This is a helper script to run the CGL server binary - always freshly built
# Usage: ./cgl [args...]

set -e

cd "$(dirname "$0")"
cd server
go build -o ../bin/cgl .
cd ..
exec bin/cgl "$@"
