// Generated by cmd/gen-protocol. Do not edit.
//
// The engine's wire protocol, from the Go types that define it.

/**
 * Stream names are not an open vocabulary: each one is an output block a
 * genre wired, so this union is the client-side mirror of the graph.
 */
export type StreamName =
  | "text"
  | "audio"
  | "image"
  | "props"
  | "flag"
  | "state"
  | "usage"
  | "error"
  ;

/** One item on the session-scoped event stream. */
export interface SessionEvent {
  readonly Stream: StreamName;
  readonly Value: string;
}

/**
 * A block reporting on itself, carried as JSON in a `state` event's value.
 * Two phases are enough: a block in the turn loop is never finished.
 */
export type Phase = "ready" | "working";

export interface BlockState {
  readonly node: string;
  readonly phase: Phase;
}

/** What one block spent on one model, cumulatively. */
export interface UsageRecord {
  readonly audioSeconds?: number;
  readonly cachedInputTokens?: number;
  readonly cost: number;
  readonly images?: number;
  readonly inputTokens?: number;
  readonly model: string;
  readonly node?: string;
  readonly outputTokens?: number;
  readonly priced: boolean;
}

/**
 * The session's spending, both ways round: per block for a graph view's
 * labels, and per model because that is what prices attach to.
 */
export interface UsageReport {
  readonly byModel: UsageRecord[];
  readonly byNode: UsageRecord[];
  readonly complete: boolean;
  readonly totalCost: number;
}

export function isSessionEvent(value: unknown): value is SessionEvent {
  if (typeof value !== "object" || value === null) return false;
  const candidate = value as Partial<SessionEvent>;
  return (
    typeof candidate.Stream === "string" &&
    typeof candidate.Value === "string"
  );
}
