// Generated by cmd/gen-protocol. Do not edit.
//
// The engine's wire protocol, from the Go types that define it.

/**
 * Stream names are not an open vocabulary: each one is an output block a
 * genre wired, so this union is the client-side mirror of the graph.
 */
export type StreamName =
  | "text"
  | "audio"
  | "image"
  | "props"
  | "flag"
  | "error"
  ;

/** One item on the session-scoped event stream. */
export interface SessionEvent {
  readonly Stream: StreamName;
  readonly Value: string;
}

export function isSessionEvent(value: unknown): value is SessionEvent {
  if (typeof value !== "object" || value === null) return false;
  const candidate = value as Partial<SessionEvent>;
  return (
    typeof candidate.Stream === "string" &&
    typeof candidate.Value === "string"
  );
}
