// Writes src/ui/fonts.css: the @font-face rules for every self-hosted font.
// Run it after adding a font here: `node fonts.mjs`. The build copies each
// referenced woff2 into dist/assets, so the player asks no third party for
// anything. Latin and Latin Extended only, which cover the languages the
// platform plays in. Every family is under the SIL Open Font License 1.1,
// except Special Elite, which is Apache 2.0.
import { readFile, writeFile } from "node:fs/promises";

/** [package, family, faces as "weight" or "weight-italic"] */
const FONTS = [
  // The platform's own face, and the theme system's sans / mono / fantasy.
  ["inter", "Inter", ["400", "500", "600", "700"]],
  ["fira-code", "Fira Code", ["400", "700"]],
  ["cinzel", "Cinzel", ["400", "700"]],
  // Skins.
  ["eb-garamond", "EB Garamond", ["400", "400-italic", "600"]],
  ["unifrakturmaguntia", "UnifrakturMaguntia", ["400"]],
  ["syne", "Syne", ["700", "800"]],
  ["space-grotesk", "Space Grotesk", ["400", "500", "700"]],
  ["alegreya", "Alegreya", ["400", "400-italic", "700"]],
  ["alegreya-sans-sc", "Alegreya Sans SC", ["500", "700"]],
  ["caveat", "Caveat", ["500", "700"]],
  ["pacifico", "Pacifico", ["400"]],
  ["quicksand", "Quicksand", ["500", "700"]],
  ["fredoka", "Fredoka", ["400", "500", "600"]],
  ["rye", "Rye", ["400"]],
  ["bree-serif", "Bree Serif", ["400"]],
  ["orbitron", "Orbitron", ["500", "700"]],
  ["share-tech-mono", "Share Tech Mono", ["400"]],
  ["marcellus", "Marcellus", ["400"]],
  ["libre-baskerville", "Libre Baskerville", ["400", "400-italic", "700"]],
  ["special-elite", "Special Elite", ["400"]],
  ["ibm-plex-sans", "IBM Plex Sans", ["400", "500", "600"]],
  ["ibm-plex-mono", "IBM Plex Mono", ["500"]],
  ["cinzel-decorative", "Cinzel Decorative", ["400", "700"]],
  ["cormorant-garamond", "Cormorant Garamond", ["500", "500-italic", "600"]],
  ["metamorphous", "Metamorphous", ["400"]],
  ["signika", "Signika", ["400", "600"]],
  ["playfair-display", "Playfair Display", ["600-italic", "700-italic"]],
  ["lora", "Lora", ["400", "400-italic", "600"]],
  ["vt323", "VT323", ["400"]],
  ["uncial-antiqua", "Uncial Antiqua", ["400"]],
  ["spectral", "Spectral", ["400", "400-italic", "600"]],
  ["jetbrains-mono", "JetBrains Mono", ["400", "700"]],
  ["im-fell-english", "IM Fell English", ["400", "400-italic"]],
  ["im-fell-english-sc", "IM Fell English SC", ["400"]],
  ["lilita-one", "Lilita One", ["400"]],
  ["nunito", "Nunito", ["500", "700"]],
  ["oswald", "Oswald", ["500", "600"]],
  ["limelight", "Limelight", ["400"]],
  ["josefin-sans", "Josefin Sans", ["600", "700"]],
  ["pirata-one", "Pirata One", ["400"]],
];

const SUBSETS = new Set(["latin", "latin-ext"]);

const rules = [];
for (const [pkg, family, faces] of FONTS) {
  for (const face of faces) {
    const [weight, italic] = face.split("-");
    const style = italic ? "italic" : "normal";
    // The per-weight file holds every subset with its unicode-range; the
    // per-subset files leave the range out.
    const css = await readFile(`node_modules/@fontsource/${pkg}/${face}.css`, "utf8");
    for (const [, name, body] of css.matchAll(/\/\* (\S+) \*\/\s*@font-face\s*\{([^}]*)\}/g)) {
      const subset = name.slice(pkg.length + 1, -`-${weight}-${style}`.length);
      if (!SUBSETS.has(subset)) continue;
      const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
      rules.push(`@font-face {
  font-family: "${family}";
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url("../../node_modules/@fontsource/${pkg}/files/${name}.woff2") format("woff2");${range ? `\n  unicode-range: ${range};` : ""}
}
`);
    }
  }
}

await writeFile(
  "src/ui/fonts.css",
  `/* Generated by fonts.mjs. Do not edit. */\n\n${rules.join("\n")}`,
);
console.log(`src/ui/fonts.css: ${rules.length} faces`);
