// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createApiKeyShareUser = `-- name: CreateApiKeyShareUser :one

INSERT INTO api_key_share_user (
  id, created_by,
  created_at, modified_by, modified_at,
  api_key_id, user_id, allow_public_sponsored_plays
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6, $7, $8
)
RETURNING id, created_by, created_at, modified_by, modified_at, api_key_id, user_id, allow_public_sponsored_plays
`

type CreateApiKeyShareUserParams struct {
	ID                        uuid.UUID
	CreatedBy                 uuid.NullUUID
	CreatedAt                 time.Time
	ModifiedBy                uuid.NullUUID
	ModifiedAt                time.Time
	ApiKeyID                  uuid.UUID
	UserID                    uuid.UUID
	AllowPublicSponsoredPlays bool
}

// api_key_share_user ---------------------------------------------------
func (q *Queries) CreateApiKeyShareUser(ctx context.Context, arg CreateApiKeyShareUserParams) (ApiKeyShareUser, error) {
	row := q.db.QueryRowContext(ctx, createApiKeyShareUser,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.ApiKeyID,
		arg.UserID,
		arg.AllowPublicSponsoredPlays,
	)
	var i ApiKeyShareUser
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.ApiKeyID,
		&i.UserID,
		&i.AllowPublicSponsoredPlays,
	)
	return i, err
}

const createApiKeyShareWorkshop = `-- name: CreateApiKeyShareWorkshop :one

INSERT INTO api_key_share_workshop (
  id, created_by,
  created_at, modified_by, modified_at,
  api_key_id, workshop_id, allow_public_sponsored_plays
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6, $7, $8
)
RETURNING id, created_by, created_at, modified_by, modified_at, api_key_id, workshop_id, allow_public_sponsored_plays
`

type CreateApiKeyShareWorkshopParams struct {
	ID                        uuid.UUID
	CreatedBy                 uuid.NullUUID
	CreatedAt                 time.Time
	ModifiedBy                uuid.NullUUID
	ModifiedAt                time.Time
	ApiKeyID                  uuid.UUID
	WorkshopID                uuid.UUID
	AllowPublicSponsoredPlays bool
}

// api_key_share_workshop ----------------------------------------------
func (q *Queries) CreateApiKeyShareWorkshop(ctx context.Context, arg CreateApiKeyShareWorkshopParams) (ApiKeyShareWorkshop, error) {
	row := q.db.QueryRowContext(ctx, createApiKeyShareWorkshop,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.ApiKeyID,
		arg.WorkshopID,
		arg.AllowPublicSponsoredPlays,
	)
	var i ApiKeyShareWorkshop
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.ApiKeyID,
		&i.WorkshopID,
		&i.AllowPublicSponsoredPlays,
	)
	return i, err
}

const deleteApiKeyShareUser = `-- name: DeleteApiKeyShareUser :exec
DELETE FROM api_key_share_user WHERE id = $1
`

func (q *Queries) DeleteApiKeyShareUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteApiKeyShareUser, id)
	return err
}

const deleteApiKeyShareWorkshop = `-- name: DeleteApiKeyShareWorkshop :exec
DELETE FROM api_key_share_workshop WHERE id = $1
`

func (q *Queries) DeleteApiKeyShareWorkshop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteApiKeyShareWorkshop, id)
	return err
}

const getApiKeyShareUserByID = `-- name: GetApiKeyShareUserByID :one
SELECT id, created_by, created_at, modified_by, modified_at, api_key_id, user_id, allow_public_sponsored_plays FROM api_key_share_user WHERE id = $1
`

func (q *Queries) GetApiKeyShareUserByID(ctx context.Context, id uuid.UUID) (ApiKeyShareUser, error) {
	row := q.db.QueryRowContext(ctx, getApiKeyShareUserByID, id)
	var i ApiKeyShareUser
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.ApiKeyID,
		&i.UserID,
		&i.AllowPublicSponsoredPlays,
	)
	return i, err
}

const getApiKeyShareWorkshopByID = `-- name: GetApiKeyShareWorkshopByID :one
SELECT id, created_by, created_at, modified_by, modified_at, api_key_id, workshop_id, allow_public_sponsored_plays FROM api_key_share_workshop WHERE id = $1
`

func (q *Queries) GetApiKeyShareWorkshopByID(ctx context.Context, id uuid.UUID) (ApiKeyShareWorkshop, error) {
	row := q.db.QueryRowContext(ctx, getApiKeyShareWorkshopByID, id)
	var i ApiKeyShareWorkshop
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.ApiKeyID,
		&i.WorkshopID,
		&i.AllowPublicSponsoredPlays,
	)
	return i, err
}

const updateApiKeyShareUser = `-- name: UpdateApiKeyShareUser :one
UPDATE api_key_share_user SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  api_key_id = $6,
  user_id = $7,
  allow_public_sponsored_plays = $8
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, api_key_id, user_id, allow_public_sponsored_plays
`

type UpdateApiKeyShareUserParams struct {
	ID                        uuid.UUID
	CreatedBy                 uuid.NullUUID
	CreatedAt                 time.Time
	ModifiedBy                uuid.NullUUID
	ModifiedAt                time.Time
	ApiKeyID                  uuid.UUID
	UserID                    uuid.UUID
	AllowPublicSponsoredPlays bool
}

func (q *Queries) UpdateApiKeyShareUser(ctx context.Context, arg UpdateApiKeyShareUserParams) (ApiKeyShareUser, error) {
	row := q.db.QueryRowContext(ctx, updateApiKeyShareUser,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.ApiKeyID,
		arg.UserID,
		arg.AllowPublicSponsoredPlays,
	)
	var i ApiKeyShareUser
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.ApiKeyID,
		&i.UserID,
		&i.AllowPublicSponsoredPlays,
	)
	return i, err
}

const updateApiKeyShareWorkshop = `-- name: UpdateApiKeyShareWorkshop :one
UPDATE api_key_share_workshop SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  api_key_id = $6,
  workshop_id = $7,
  allow_public_sponsored_plays = $8
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, api_key_id, workshop_id, allow_public_sponsored_plays
`

type UpdateApiKeyShareWorkshopParams struct {
	ID                        uuid.UUID
	CreatedBy                 uuid.NullUUID
	CreatedAt                 time.Time
	ModifiedBy                uuid.NullUUID
	ModifiedAt                time.Time
	ApiKeyID                  uuid.UUID
	WorkshopID                uuid.UUID
	AllowPublicSponsoredPlays bool
}

func (q *Queries) UpdateApiKeyShareWorkshop(ctx context.Context, arg UpdateApiKeyShareWorkshopParams) (ApiKeyShareWorkshop, error) {
	row := q.db.QueryRowContext(ctx, updateApiKeyShareWorkshop,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.ApiKeyID,
		arg.WorkshopID,
		arg.AllowPublicSponsoredPlays,
	)
	var i ApiKeyShareWorkshop
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.ApiKeyID,
		&i.WorkshopID,
		&i.AllowPublicSponsoredPlays,
	)
	return i, err
}
