// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup_log.sql

package db

import (
	"context"
)

const getLatestBackup = `-- name: GetLatestBackup :one

SELECT
  id,
  started_at,
  finished_at,
  success,
  filename,
  size_bytes,
  error
FROM backup_log
ORDER BY finished_at DESC
LIMIT 1
`

// Backup Log queries
func (q *Queries) GetLatestBackup(ctx context.Context) (BackupLog, error) {
	row := q.db.QueryRowContext(ctx, getLatestBackup)
	var i BackupLog
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Success,
		&i.Filename,
		&i.SizeBytes,
		&i.Error,
	)
	return i, err
}
