// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createGame = `-- name: CreateGame :one



INSERT INTO game (
  id, created_by,
  created_at, modified_by, modified_at,
  name, description, icon,
  public, public_sponsored_api_key_id,
  private_share_hash, private_sponsored_api_key_id,
  system_message_scenario, system_message_game_start,
  image_style, css, status_fields,
  first_message, first_status, first_image
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6, $7, $8,
  $9, $10,
  $11, $12,
  $13, $14,
  $15, $16, $17,
  $18, $19, $20
)
RETURNING id, created_by, created_at, modified_by, modified_at, name, description, icon, public, public_sponsored_api_key_id, private_share_hash, private_sponsored_api_key_id, system_message_scenario, system_message_game_start, image_style, css, status_fields, first_message, first_status, first_image
`

type CreateGameParams struct {
	ID                       uuid.UUID
	CreatedBy                uuid.NullUUID
	CreatedAt                time.Time
	ModifiedBy               uuid.NullUUID
	ModifiedAt               time.Time
	Name                     string
	Description              sql.NullString
	Icon                     []byte
	Public                   bool
	PublicSponsoredApiKeyID  uuid.NullUUID
	PrivateShareHash         sql.NullString
	PrivateSponsoredApiKeyID uuid.NullUUID
	SystemMessageScenario    string
	SystemMessageGameStart   string
	ImageStyle               string
	Css                      sql.NullString
	StatusFields             string
	FirstMessage             sql.NullString
	FirstStatus              sql.NullString
	FirstImage               []byte
}

// Basic CRUD queries for core entities
// Exactly four per table: create, read by id, update by id, delete by id.
// game -----------------------------------------------------------------
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Public,
		arg.PublicSponsoredApiKeyID,
		arg.PrivateShareHash,
		arg.PrivateSponsoredApiKeyID,
		arg.SystemMessageScenario,
		arg.SystemMessageGameStart,
		arg.ImageStyle,
		arg.Css,
		arg.StatusFields,
		arg.FirstMessage,
		arg.FirstStatus,
		arg.FirstImage,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Public,
		&i.PublicSponsoredApiKeyID,
		&i.PrivateShareHash,
		&i.PrivateSponsoredApiKeyID,
		&i.SystemMessageScenario,
		&i.SystemMessageGameStart,
		&i.ImageStyle,
		&i.Css,
		&i.StatusFields,
		&i.FirstMessage,
		&i.FirstStatus,
		&i.FirstImage,
	)
	return i, err
}

const createGameSession = `-- name: CreateGameSession :one

INSERT INTO game_session (
  id, created_by,
  created_at, modified_by, modified_at,
  game_id, user_id, api_key_id,
  model, model_session,
  image_style, status_fields
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6, $7, $8,
  $9, $10,
  $11, $12
)
RETURNING id, created_by, created_at, modified_by, modified_at, game_id, user_id, api_key_id, model, model_session, image_style, status_fields
`

type CreateGameSessionParams struct {
	ID           uuid.UUID
	CreatedBy    uuid.NullUUID
	CreatedAt    time.Time
	ModifiedBy   uuid.NullUUID
	ModifiedAt   time.Time
	GameID       uuid.UUID
	UserID       uuid.UUID
	ApiKeyID     uuid.UUID
	Model        string
	ModelSession json.RawMessage
	ImageStyle   string
	StatusFields string
}

// game_session ---------------------------------------------------------
func (q *Queries) CreateGameSession(ctx context.Context, arg CreateGameSessionParams) (GameSession, error) {
	row := q.db.QueryRowContext(ctx, createGameSession,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.GameID,
		arg.UserID,
		arg.ApiKeyID,
		arg.Model,
		arg.ModelSession,
		arg.ImageStyle,
		arg.StatusFields,
	)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.GameID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Model,
		&i.ModelSession,
		&i.ImageStyle,
		&i.StatusFields,
	)
	return i, err
}

const createGameSessionMessage = `-- name: CreateGameSessionMessage :one

INSERT INTO game_session_message (
  id, created_by,
  created_at, modified_by, modified_at,
  game_session_id,
  type, message,
  status, image_prompt, image
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6,
  $7, $8,
  $9, $10, $11
)
RETURNING id, created_by, created_at, modified_by, modified_at, game_session_id, type, message, status, image_prompt, image
`

type CreateGameSessionMessageParams struct {
	ID            uuid.UUID
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	ModifiedBy    uuid.NullUUID
	ModifiedAt    time.Time
	GameSessionID uuid.UUID
	Type          string
	Message       string
	Status        sql.NullString
	ImagePrompt   sql.NullString
	Image         []byte
}

// game_session_message -------------------------------------------------
func (q *Queries) CreateGameSessionMessage(ctx context.Context, arg CreateGameSessionMessageParams) (GameSessionMessage, error) {
	row := q.db.QueryRowContext(ctx, createGameSessionMessage,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.GameSessionID,
		arg.Type,
		arg.Message,
		arg.Status,
		arg.ImagePrompt,
		arg.Image,
	)
	var i GameSessionMessage
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.GameSessionID,
		&i.Type,
		&i.Message,
		&i.Status,
		&i.ImagePrompt,
		&i.Image,
	)
	return i, err
}

const createGameTag = `-- name: CreateGameTag :one

INSERT INTO game_tag (
  id, created_by,
  created_at, modified_by, modified_at,
  game_id, tag
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6, $7
)
RETURNING id, created_by, created_at, modified_by, modified_at, game_id, tag
`

type CreateGameTagParams struct {
	ID         uuid.UUID
	CreatedBy  uuid.NullUUID
	CreatedAt  time.Time
	ModifiedBy uuid.NullUUID
	ModifiedAt time.Time
	GameID     uuid.UUID
	Tag        string
}

// game_tag -------------------------------------------------------------
func (q *Queries) CreateGameTag(ctx context.Context, arg CreateGameTagParams) (GameTag, error) {
	row := q.db.QueryRowContext(ctx, createGameTag,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.GameID,
		arg.Tag,
	)
	var i GameTag
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.GameID,
		&i.Tag,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM game WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGame, id)
	return err
}

const deleteGameSession = `-- name: DeleteGameSession :exec
DELETE FROM game_session WHERE id = $1
`

func (q *Queries) DeleteGameSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGameSession, id)
	return err
}

const deleteGameSessionMessage = `-- name: DeleteGameSessionMessage :exec
DELETE FROM game_session_message WHERE id = $1
`

func (q *Queries) DeleteGameSessionMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGameSessionMessage, id)
	return err
}

const deleteGameTag = `-- name: DeleteGameTag :exec
DELETE FROM game_tag WHERE id = $1
`

func (q *Queries) DeleteGameTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGameTag, id)
	return err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, created_by, created_at, modified_by, modified_at, name, description, icon, public, public_sponsored_api_key_id, private_share_hash, private_sponsored_api_key_id, system_message_scenario, system_message_game_start, image_style, css, status_fields, first_message, first_status, first_image FROM game WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Public,
		&i.PublicSponsoredApiKeyID,
		&i.PrivateShareHash,
		&i.PrivateSponsoredApiKeyID,
		&i.SystemMessageScenario,
		&i.SystemMessageGameStart,
		&i.ImageStyle,
		&i.Css,
		&i.StatusFields,
		&i.FirstMessage,
		&i.FirstStatus,
		&i.FirstImage,
	)
	return i, err
}

const getGameByPrivateShareHash = `-- name: GetGameByPrivateShareHash :one
SELECT id, created_by, created_at, modified_by, modified_at, name, description, icon, public, public_sponsored_api_key_id, private_share_hash, private_sponsored_api_key_id, system_message_scenario, system_message_game_start, image_style, css, status_fields, first_message, first_status, first_image FROM game WHERE private_share_hash = $1
`

func (q *Queries) GetGameByPrivateShareHash(ctx context.Context, privateShareHash sql.NullString) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByPrivateShareHash, privateShareHash)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Public,
		&i.PublicSponsoredApiKeyID,
		&i.PrivateShareHash,
		&i.PrivateSponsoredApiKeyID,
		&i.SystemMessageScenario,
		&i.SystemMessageGameStart,
		&i.ImageStyle,
		&i.Css,
		&i.StatusFields,
		&i.FirstMessage,
		&i.FirstStatus,
		&i.FirstImage,
	)
	return i, err
}

const getGameIDsVisibleToUser = `-- name: GetGameIDsVisibleToUser :many
SELECT id FROM game WHERE created_by = $1 OR public = true
`

func (q *Queries) GetGameIDsVisibleToUser(ctx context.Context, createdBy uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getGameIDsVisibleToUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameSessionByID = `-- name: GetGameSessionByID :one
SELECT id, created_by, created_at, modified_by, modified_at, game_id, user_id, api_key_id, model, model_session, image_style, status_fields FROM game_session WHERE id = $1
`

func (q *Queries) GetGameSessionByID(ctx context.Context, id uuid.UUID) (GameSession, error) {
	row := q.db.QueryRowContext(ctx, getGameSessionByID, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.GameID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Model,
		&i.ModelSession,
		&i.ImageStyle,
		&i.StatusFields,
	)
	return i, err
}

const getGameSessionMessageByID = `-- name: GetGameSessionMessageByID :one
SELECT id, created_by, created_at, modified_by, modified_at, game_session_id, type, message, status, image_prompt, image FROM game_session_message WHERE id = $1
`

func (q *Queries) GetGameSessionMessageByID(ctx context.Context, id uuid.UUID) (GameSessionMessage, error) {
	row := q.db.QueryRowContext(ctx, getGameSessionMessageByID, id)
	var i GameSessionMessage
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.GameSessionID,
		&i.Type,
		&i.Message,
		&i.Status,
		&i.ImagePrompt,
		&i.Image,
	)
	return i, err
}

const getGameTagByID = `-- name: GetGameTagByID :one
SELECT id, created_by, created_at, modified_by, modified_at, game_id, tag FROM game_tag WHERE id = $1
`

func (q *Queries) GetGameTagByID(ctx context.Context, id uuid.UUID) (GameTag, error) {
	row := q.db.QueryRowContext(ctx, getGameTagByID, id)
	var i GameTag
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.GameID,
		&i.Tag,
	)
	return i, err
}

const getGameTagsByGameID = `-- name: GetGameTagsByGameID :many
SELECT id, created_by, created_at, modified_by, modified_at, game_id, tag FROM game_tag WHERE game_id = $1
`

func (q *Queries) GetGameTagsByGameID(ctx context.Context, gameID uuid.UUID) ([]GameTag, error) {
	rows, err := q.db.QueryContext(ctx, getGameTagsByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameTag
	for rows.Next() {
		var i GameTag
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
			&i.GameID,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesVisibleToUser = `-- name: GetGamesVisibleToUser :many
SELECT id, created_by, created_at, modified_by, modified_at, name, description, icon, public, public_sponsored_api_key_id, private_share_hash, private_sponsored_api_key_id, system_message_scenario, system_message_game_start, image_style, css, status_fields, first_message, first_status, first_image FROM game WHERE created_by = $1 OR public = true ORDER BY created_at DESC
`

func (q *Queries) GetGamesVisibleToUser(ctx context.Context, createdBy uuid.NullUUID) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, getGamesVisibleToUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Public,
			&i.PublicSponsoredApiKeyID,
			&i.PrivateShareHash,
			&i.PrivateSponsoredApiKeyID,
			&i.SystemMessageScenario,
			&i.SystemMessageGameStart,
			&i.ImageStyle,
			&i.Css,
			&i.StatusFields,
			&i.FirstMessage,
			&i.FirstStatus,
			&i.FirstImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicGames = `-- name: GetPublicGames :many
SELECT id, created_by, created_at, modified_by, modified_at, name, description, icon, public, public_sponsored_api_key_id, private_share_hash, private_sponsored_api_key_id, system_message_scenario, system_message_game_start, image_style, css, status_fields, first_message, first_status, first_image FROM game WHERE public = true ORDER BY created_at DESC
`

func (q *Queries) GetPublicGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, getPublicGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Public,
			&i.PublicSponsoredApiKeyID,
			&i.PrivateShareHash,
			&i.PrivateSponsoredApiKeyID,
			&i.SystemMessageScenario,
			&i.SystemMessageGameStart,
			&i.ImageStyle,
			&i.Css,
			&i.StatusFields,
			&i.FirstMessage,
			&i.FirstStatus,
			&i.FirstImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :one
UPDATE game SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  name = $6,
  description = $7,
  icon = $8,
  public = $9,
  public_sponsored_api_key_id = $10,
  private_share_hash = $11,
  private_sponsored_api_key_id = $12,
  system_message_scenario = $13,
  system_message_game_start = $14,
  image_style = $15,
  css = $16,
  status_fields = $17,
  first_message = $18,
  first_status = $19,
  first_image = $20
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, name, description, icon, public, public_sponsored_api_key_id, private_share_hash, private_sponsored_api_key_id, system_message_scenario, system_message_game_start, image_style, css, status_fields, first_message, first_status, first_image
`

type UpdateGameParams struct {
	ID                       uuid.UUID
	CreatedBy                uuid.NullUUID
	CreatedAt                time.Time
	ModifiedBy               uuid.NullUUID
	ModifiedAt               time.Time
	Name                     string
	Description              sql.NullString
	Icon                     []byte
	Public                   bool
	PublicSponsoredApiKeyID  uuid.NullUUID
	PrivateShareHash         sql.NullString
	PrivateSponsoredApiKeyID uuid.NullUUID
	SystemMessageScenario    string
	SystemMessageGameStart   string
	ImageStyle               string
	Css                      sql.NullString
	StatusFields             string
	FirstMessage             sql.NullString
	FirstStatus              sql.NullString
	FirstImage               []byte
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateGame,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Public,
		arg.PublicSponsoredApiKeyID,
		arg.PrivateShareHash,
		arg.PrivateSponsoredApiKeyID,
		arg.SystemMessageScenario,
		arg.SystemMessageGameStart,
		arg.ImageStyle,
		arg.Css,
		arg.StatusFields,
		arg.FirstMessage,
		arg.FirstStatus,
		arg.FirstImage,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Public,
		&i.PublicSponsoredApiKeyID,
		&i.PrivateShareHash,
		&i.PrivateSponsoredApiKeyID,
		&i.SystemMessageScenario,
		&i.SystemMessageGameStart,
		&i.ImageStyle,
		&i.Css,
		&i.StatusFields,
		&i.FirstMessage,
		&i.FirstStatus,
		&i.FirstImage,
	)
	return i, err
}

const updateGameSession = `-- name: UpdateGameSession :one
UPDATE game_session SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  game_id = $6,
  user_id = $7,
  api_key_id = $8,
  model = $9,
  model_session = $10,
  image_style = $11,
  status_fields = $12
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, game_id, user_id, api_key_id, model, model_session, image_style, status_fields
`

type UpdateGameSessionParams struct {
	ID           uuid.UUID
	CreatedBy    uuid.NullUUID
	CreatedAt    time.Time
	ModifiedBy   uuid.NullUUID
	ModifiedAt   time.Time
	GameID       uuid.UUID
	UserID       uuid.UUID
	ApiKeyID     uuid.UUID
	Model        string
	ModelSession json.RawMessage
	ImageStyle   string
	StatusFields string
}

func (q *Queries) UpdateGameSession(ctx context.Context, arg UpdateGameSessionParams) (GameSession, error) {
	row := q.db.QueryRowContext(ctx, updateGameSession,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.GameID,
		arg.UserID,
		arg.ApiKeyID,
		arg.Model,
		arg.ModelSession,
		arg.ImageStyle,
		arg.StatusFields,
	)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.GameID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Model,
		&i.ModelSession,
		&i.ImageStyle,
		&i.StatusFields,
	)
	return i, err
}

const updateGameSessionMessage = `-- name: UpdateGameSessionMessage :one
UPDATE game_session_message SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  game_session_id = $6,
  type = $7,
  message = $8,
  status = $9,
  image_prompt = $10,
  image = $11
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, game_session_id, type, message, status, image_prompt, image
`

type UpdateGameSessionMessageParams struct {
	ID            uuid.UUID
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	ModifiedBy    uuid.NullUUID
	ModifiedAt    time.Time
	GameSessionID uuid.UUID
	Type          string
	Message       string
	Status        sql.NullString
	ImagePrompt   sql.NullString
	Image         []byte
}

func (q *Queries) UpdateGameSessionMessage(ctx context.Context, arg UpdateGameSessionMessageParams) (GameSessionMessage, error) {
	row := q.db.QueryRowContext(ctx, updateGameSessionMessage,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.GameSessionID,
		arg.Type,
		arg.Message,
		arg.Status,
		arg.ImagePrompt,
		arg.Image,
	)
	var i GameSessionMessage
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.GameSessionID,
		&i.Type,
		&i.Message,
		&i.Status,
		&i.ImagePrompt,
		&i.Image,
	)
	return i, err
}

const updateGameTag = `-- name: UpdateGameTag :one
UPDATE game_tag SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  game_id = $6,
  tag = $7
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, game_id, tag
`

type UpdateGameTagParams struct {
	ID         uuid.UUID
	CreatedBy  uuid.NullUUID
	CreatedAt  time.Time
	ModifiedBy uuid.NullUUID
	ModifiedAt time.Time
	GameID     uuid.UUID
	Tag        string
}

func (q *Queries) UpdateGameTag(ctx context.Context, arg UpdateGameTagParams) (GameTag, error) {
	row := q.db.QueryRowContext(ctx, updateGameTag,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.GameID,
		arg.Tag,
	)
	var i GameTag
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.GameID,
		&i.Tag,
	)
	return i, err
}
