// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_share.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countGuestUsersByShareID = `-- name: CountGuestUsersByShareID :one
SELECT COUNT(*)::int AS count FROM app_user WHERE private_share_id = $1
`

func (q *Queries) CountGuestUsersByShareID(ctx context.Context, privateShareID uuid.NullUUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countGuestUsersByShareID, privateShareID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createGameShare = `-- name: CreateGameShare :one

INSERT INTO game_share (game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by, created_at
`

type CreateGameShareParams struct {
	GameID        uuid.UUID
	Token         string
	ApiKeyShareID uuid.UUID
	InstitutionID uuid.NullUUID
	WorkshopID    uuid.NullUUID
	Remaining     sql.NullInt32
	CreatedBy     uuid.NullUUID
}

// game_share queries
func (q *Queries) CreateGameShare(ctx context.Context, arg CreateGameShareParams) (GameShare, error) {
	row := q.db.QueryRowContext(ctx, createGameShare,
		arg.GameID,
		arg.Token,
		arg.ApiKeyShareID,
		arg.InstitutionID,
		arg.WorkshopID,
		arg.Remaining,
		arg.CreatedBy,
	)
	var i GameShare
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Token,
		&i.ApiKeyShareID,
		&i.InstitutionID,
		&i.WorkshopID,
		&i.Remaining,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const decrementGameShareRemaining = `-- name: DecrementGameShareRemaining :one
UPDATE game_share SET remaining = CASE
  WHEN remaining IS NULL THEN NULL
  ELSE remaining - 1
END
WHERE id = $1 AND (remaining IS NULL OR remaining > 0) RETURNING id, game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by, created_at
`

// Atomically decrements the remaining counter. Returns the share if successful.
// Succeeds when: remaining is NULL (unlimited) or remaining > 0.
func (q *Queries) DecrementGameShareRemaining(ctx context.Context, id uuid.UUID) (GameShare, error) {
	row := q.db.QueryRowContext(ctx, decrementGameShareRemaining, id)
	var i GameShare
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Token,
		&i.ApiKeyShareID,
		&i.InstitutionID,
		&i.WorkshopID,
		&i.Remaining,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGameShare = `-- name: DeleteGameShare :exec
DELETE FROM game_share WHERE id = $1
`

func (q *Queries) DeleteGameShare(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGameShare, id)
	return err
}

const deleteGameSharesByApiKeyShareID = `-- name: DeleteGameSharesByApiKeyShareID :exec
DELETE FROM game_share WHERE api_key_share_id = $1
`

// Cascade cleanup: when an api_key_share is deleted, remove all game_shares referencing it
func (q *Queries) DeleteGameSharesByApiKeyShareID(ctx context.Context, apiKeyShareID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGameSharesByApiKeyShareID, apiKeyShareID)
	return err
}

const deleteGameSharesByGameID = `-- name: DeleteGameSharesByGameID :exec
DELETE FROM game_share WHERE game_id = $1
`

func (q *Queries) DeleteGameSharesByGameID(ctx context.Context, gameID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGameSharesByGameID, gameID)
	return err
}

const deleteGuestSessionMessagesByShareID = `-- name: DeleteGuestSessionMessagesByShareID :exec

DELETE FROM game_session_message WHERE game_session_id IN (
  SELECT gs.id FROM game_session gs
  JOIN app_user u ON u.id = gs.user_id
  WHERE u.private_share_id = $1
)
`

// Guest data cleanup by share ID
func (q *Queries) DeleteGuestSessionMessagesByShareID(ctx context.Context, privateShareID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteGuestSessionMessagesByShareID, privateShareID)
	return err
}

const deleteGuestSessionsByShareID = `-- name: DeleteGuestSessionsByShareID :exec
DELETE FROM game_session WHERE user_id IN (
  SELECT id FROM app_user WHERE private_share_id = $1
)
`

func (q *Queries) DeleteGuestSessionsByShareID(ctx context.Context, privateShareID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteGuestSessionsByShareID, privateShareID)
	return err
}

const deleteGuestUsersByShareID = `-- name: DeleteGuestUsersByShareID :exec
DELETE FROM app_user WHERE private_share_id = $1
`

func (q *Queries) DeleteGuestUsersByShareID(ctx context.Context, privateShareID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteGuestUsersByShareID, privateShareID)
	return err
}

const getGameShareByID = `-- name: GetGameShareByID :one
SELECT id, game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by, created_at FROM game_share WHERE id = $1
`

func (q *Queries) GetGameShareByID(ctx context.Context, id uuid.UUID) (GameShare, error) {
	row := q.db.QueryRowContext(ctx, getGameShareByID, id)
	var i GameShare
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Token,
		&i.ApiKeyShareID,
		&i.InstitutionID,
		&i.WorkshopID,
		&i.Remaining,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGameShareByToken = `-- name: GetGameShareByToken :one
SELECT id, game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by, created_at FROM game_share WHERE token = $1
`

func (q *Queries) GetGameShareByToken(ctx context.Context, token string) (GameShare, error) {
	row := q.db.QueryRowContext(ctx, getGameShareByToken, token)
	var i GameShare
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Token,
		&i.ApiKeyShareID,
		&i.InstitutionID,
		&i.WorkshopID,
		&i.Remaining,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGameShareIDsByApiKeyID = `-- name: GetGameShareIDsByApiKeyID :many
SELECT gs.id FROM game_share gs
JOIN api_key_share aks ON aks.id = gs.api_key_share_id
WHERE aks.api_key_id = $1
`

// Find all game_share IDs that reference any api_key_share belonging to a given api_key
func (q *Queries) GetGameShareIDsByApiKeyID(ctx context.Context, apiKeyID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getGameShareIDsByApiKeyID, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameShareIDsByApiKeyShareID = `-- name: GetGameShareIDsByApiKeyShareID :many
SELECT id FROM game_share WHERE api_key_share_id = $1
`

// Find game_share IDs that reference a specific api_key_share (for guest cleanup before deletion)
func (q *Queries) GetGameShareIDsByApiKeyShareID(ctx context.Context, apiKeyShareID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getGameShareIDsByApiKeyShareID, apiKeyShareID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameSharesByGameID = `-- name: GetGameSharesByGameID :many
SELECT id, game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by, created_at FROM game_share WHERE game_id = $1 ORDER BY created_at
`

func (q *Queries) GetGameSharesByGameID(ctx context.Context, gameID uuid.UUID) ([]GameShare, error) {
	rows, err := q.db.QueryContext(ctx, getGameSharesByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameShare
	for rows.Next() {
		var i GameShare
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Token,
			&i.ApiKeyShareID,
			&i.InstitutionID,
			&i.WorkshopID,
			&i.Remaining,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameSharesByGameIDAndCreator = `-- name: GetGameSharesByGameIDAndCreator :many
SELECT id, game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by, created_at FROM game_share WHERE game_id = $1 AND created_by = $2 AND workshop_id IS NULL ORDER BY created_at
`

type GetGameSharesByGameIDAndCreatorParams struct {
	GameID    uuid.UUID
	CreatedBy uuid.NullUUID
}

// Personal context: only non-workshop shares (workshop shares belong to their workshop context)
func (q *Queries) GetGameSharesByGameIDAndCreator(ctx context.Context, arg GetGameSharesByGameIDAndCreatorParams) ([]GameShare, error) {
	rows, err := q.db.QueryContext(ctx, getGameSharesByGameIDAndCreator, arg.GameID, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameShare
	for rows.Next() {
		var i GameShare
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Token,
			&i.ApiKeyShareID,
			&i.InstitutionID,
			&i.WorkshopID,
			&i.Remaining,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameSharesByGameIDAndInstitution = `-- name: GetGameSharesByGameIDAndInstitution :many
SELECT id, game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by, created_at FROM game_share WHERE game_id = $1 AND institution_id = $2 AND workshop_id IS NULL ORDER BY created_at
`

type GetGameSharesByGameIDAndInstitutionParams struct {
	GameID        uuid.UUID
	InstitutionID uuid.NullUUID
}

// Org shares: shares belonging to an institution (excludes workshop shares which have their own context)
func (q *Queries) GetGameSharesByGameIDAndInstitution(ctx context.Context, arg GetGameSharesByGameIDAndInstitutionParams) ([]GameShare, error) {
	rows, err := q.db.QueryContext(ctx, getGameSharesByGameIDAndInstitution, arg.GameID, arg.InstitutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameShare
	for rows.Next() {
		var i GameShare
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Token,
			&i.ApiKeyShareID,
			&i.InstitutionID,
			&i.WorkshopID,
			&i.Remaining,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameSharesByGameIDAndWorkshop = `-- name: GetGameSharesByGameIDAndWorkshop :many
SELECT id, game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by, created_at FROM game_share WHERE game_id = $1 AND workshop_id = $2 ORDER BY created_at
`

type GetGameSharesByGameIDAndWorkshopParams struct {
	GameID     uuid.UUID
	WorkshopID uuid.NullUUID
}

func (q *Queries) GetGameSharesByGameIDAndWorkshop(ctx context.Context, arg GetGameSharesByGameIDAndWorkshopParams) ([]GameShare, error) {
	rows, err := q.db.QueryContext(ctx, getGameSharesByGameIDAndWorkshop, arg.GameID, arg.WorkshopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameShare
	for rows.Next() {
		var i GameShare
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Token,
			&i.ApiKeyShareID,
			&i.InstitutionID,
			&i.WorkshopID,
			&i.Remaining,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameSharesWithGameByApiKeyID = `-- name: GetGameSharesWithGameByApiKeyID :many
SELECT gs.id, gs.game_id, gs.token, gs.api_key_share_id, gs.institution_id, gs.workshop_id, gs.remaining, gs.created_by, gs.created_at, g.name as game_name FROM game_share gs
JOIN game g ON g.id = gs.game_id
JOIN api_key_share aks ON aks.id = gs.api_key_share_id
WHERE aks.api_key_id = $1 ORDER BY gs.created_at
`

type GetGameSharesWithGameByApiKeyIDRow struct {
	ID            uuid.UUID
	GameID        uuid.UUID
	Token         string
	ApiKeyShareID uuid.UUID
	InstitutionID uuid.NullUUID
	WorkshopID    uuid.NullUUID
	Remaining     sql.NullInt32
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	GameName      string
}

// Get all game shares with game name for any api_key_share belonging to a given api_key
func (q *Queries) GetGameSharesWithGameByApiKeyID(ctx context.Context, apiKeyID uuid.UUID) ([]GetGameSharesWithGameByApiKeyIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getGameSharesWithGameByApiKeyID, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameSharesWithGameByApiKeyIDRow
	for rows.Next() {
		var i GetGameSharesWithGameByApiKeyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Token,
			&i.ApiKeyShareID,
			&i.InstitutionID,
			&i.WorkshopID,
			&i.Remaining,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.GameName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameSharesWithGameByApiKeyShareID = `-- name: GetGameSharesWithGameByApiKeyShareID :many
SELECT gs.id, gs.game_id, gs.token, gs.api_key_share_id, gs.institution_id, gs.workshop_id, gs.remaining, gs.created_by, gs.created_at, g.name as game_name FROM game_share gs
JOIN game g ON g.id = gs.game_id
WHERE gs.api_key_share_id = $1 ORDER BY gs.created_at
`

type GetGameSharesWithGameByApiKeyShareIDRow struct {
	ID            uuid.UUID
	GameID        uuid.UUID
	Token         string
	ApiKeyShareID uuid.UUID
	InstitutionID uuid.NullUUID
	WorkshopID    uuid.NullUUID
	Remaining     sql.NullInt32
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	GameName      string
}

// Get game shares with game name for a specific api_key_share (for display in API key management)
func (q *Queries) GetGameSharesWithGameByApiKeyShareID(ctx context.Context, apiKeyShareID uuid.UUID) ([]GetGameSharesWithGameByApiKeyShareIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getGameSharesWithGameByApiKeyShareID, apiKeyShareID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameSharesWithGameByApiKeyShareIDRow
	for rows.Next() {
		var i GetGameSharesWithGameByApiKeyShareIDRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Token,
			&i.ApiKeyShareID,
			&i.InstitutionID,
			&i.WorkshopID,
			&i.Remaining,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.GameName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkshopGameShare = `-- name: GetWorkshopGameShare :one
SELECT id, game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by, created_at FROM game_share WHERE game_id = $1 AND workshop_id = $2
`

type GetWorkshopGameShareParams struct {
	GameID     uuid.UUID
	WorkshopID uuid.NullUUID
}

// Find existing workshop share for a game (reuse instead of creating duplicates)
func (q *Queries) GetWorkshopGameShare(ctx context.Context, arg GetWorkshopGameShareParams) (GameShare, error) {
	row := q.db.QueryRowContext(ctx, getWorkshopGameShare, arg.GameID, arg.WorkshopID)
	var i GameShare
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Token,
		&i.ApiKeyShareID,
		&i.InstitutionID,
		&i.WorkshopID,
		&i.Remaining,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateGameShareRemaining = `-- name: UpdateGameShareRemaining :one
UPDATE game_share SET remaining = $2 WHERE id = $1 RETURNING id, game_id, token, api_key_share_id, institution_id, workshop_id, remaining, created_by, created_at
`

type UpdateGameShareRemainingParams struct {
	ID        uuid.UUID
	Remaining sql.NullInt32
}

func (q *Queries) UpdateGameShareRemaining(ctx context.Context, arg UpdateGameShareRemainingParams) (GameShare, error) {
	row := q.db.QueryRowContext(ctx, updateGameShareRemaining, arg.ID, arg.Remaining)
	var i GameShare
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Token,
		&i.ApiKeyShareID,
		&i.InstitutionID,
		&i.WorkshopID,
		&i.Remaining,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
