// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: institution.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const clearInstitutionFreeUseApiKeyShare = `-- name: ClearInstitutionFreeUseApiKeyShare :exec
UPDATE institution SET free_use_api_key_share_id = NULL WHERE id = $1
`

func (q *Queries) ClearInstitutionFreeUseApiKeyShare(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearInstitutionFreeUseApiKeyShare, id)
	return err
}

const createInstitution = `-- name: CreateInstitution :one

INSERT INTO institution (
  id, created_by,
  created_at, modified_by, modified_at,
  name
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6
)
RETURNING id, created_by, created_at, modified_by, modified_at, name, deleted_at, free_use_api_key_share_id, free_use_ai_quality_tier
`

type CreateInstitutionParams struct {
	ID         uuid.UUID
	CreatedBy  uuid.NullUUID
	CreatedAt  time.Time
	ModifiedBy uuid.NullUUID
	ModifiedAt time.Time
	Name       string
}

// institution ----------------------------------------------------------
func (q *Queries) CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (Institution, error) {
	row := q.db.QueryRowContext(ctx, createInstitution,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
	)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.DeletedAt,
		&i.FreeUseApiKeyShareID,
		&i.FreeUseAiQualityTier,
	)
	return i, err
}

const createWorkshop = `-- name: CreateWorkshop :one

INSERT INTO workshop (
  id, created_by,
  created_at, modified_by, modified_at,
  name, institution_id, active, public, default_api_key_share_id,
  ai_quality_tier, show_public_games, show_other_participants_games,
  design_editing_enabled, is_paused
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6, $7, $8, $9, $10,
  $11, $12, $13,
  $14, $15
)
RETURNING id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at, default_api_key_share_id, ai_quality_tier, show_public_games, show_other_participants_games, design_editing_enabled, is_paused
`

type CreateWorkshopParams struct {
	ID                         uuid.UUID
	CreatedBy                  uuid.NullUUID
	CreatedAt                  time.Time
	ModifiedBy                 uuid.NullUUID
	ModifiedAt                 time.Time
	Name                       string
	InstitutionID              uuid.UUID
	Active                     bool
	Public                     bool
	DefaultApiKeyShareID       uuid.NullUUID
	AiQualityTier              sql.NullString
	ShowPublicGames            bool
	ShowOtherParticipantsGames bool
	DesignEditingEnabled       bool
	IsPaused                   bool
}

// workshop -------------------------------------------------------------
func (q *Queries) CreateWorkshop(ctx context.Context, arg CreateWorkshopParams) (Workshop, error) {
	row := q.db.QueryRowContext(ctx, createWorkshop,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
		arg.InstitutionID,
		arg.Active,
		arg.Public,
		arg.DefaultApiKeyShareID,
		arg.AiQualityTier,
		arg.ShowPublicGames,
		arg.ShowOtherParticipantsGames,
		arg.DesignEditingEnabled,
		arg.IsPaused,
	)
	var i Workshop
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.InstitutionID,
		&i.Active,
		&i.Public,
		&i.DeletedAt,
		&i.DefaultApiKeyShareID,
		&i.AiQualityTier,
		&i.ShowPublicGames,
		&i.ShowOtherParticipantsGames,
		&i.DesignEditingEnabled,
		&i.IsPaused,
	)
	return i, err
}

const createWorkshopParticipant = `-- name: CreateWorkshopParticipant :one

INSERT INTO workshop_participant (
  id, created_by,
  created_at, modified_by, modified_at,
  workshop_id, name, access_token, active
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6, $7, $8, $9
)
RETURNING id, created_by, created_at, modified_by, modified_at, workshop_id, name, access_token, active
`

type CreateWorkshopParticipantParams struct {
	ID          uuid.UUID
	CreatedBy   uuid.NullUUID
	CreatedAt   time.Time
	ModifiedBy  uuid.NullUUID
	ModifiedAt  time.Time
	WorkshopID  uuid.UUID
	Name        string
	AccessToken string
	Active      bool
}

// workshop_participant -------------------------------------------------
func (q *Queries) CreateWorkshopParticipant(ctx context.Context, arg CreateWorkshopParticipantParams) (WorkshopParticipant, error) {
	row := q.db.QueryRowContext(ctx, createWorkshopParticipant,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.WorkshopID,
		arg.Name,
		arg.AccessToken,
		arg.Active,
	)
	var i WorkshopParticipant
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.WorkshopID,
		&i.Name,
		&i.AccessToken,
		&i.Active,
	)
	return i, err
}

const deleteApiKeySharesByInstitution = `-- name: DeleteApiKeySharesByInstitution :exec
DELETE FROM api_key_share WHERE institution_id = $1
`

func (q *Queries) DeleteApiKeySharesByInstitution(ctx context.Context, institutionID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteApiKeySharesByInstitution, institutionID)
	return err
}

const deleteInvitesByInstitution = `-- name: DeleteInvitesByInstitution :exec
DELETE FROM user_role_invite WHERE institution_id = $1
`

func (q *Queries) DeleteInvitesByInstitution(ctx context.Context, institutionID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvitesByInstitution, institutionID)
	return err
}

const deleteUserRolesByInstitution = `-- name: DeleteUserRolesByInstitution :exec
DELETE FROM user_role WHERE institution_id = $1
`

func (q *Queries) DeleteUserRolesByInstitution(ctx context.Context, institutionID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserRolesByInstitution, institutionID)
	return err
}

const deleteWorkshop = `-- name: DeleteWorkshop :exec
UPDATE workshop SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteWorkshop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkshop, id)
	return err
}

const deleteWorkshopParticipant = `-- name: DeleteWorkshopParticipant :exec
DELETE FROM workshop_participant WHERE id = $1
`

func (q *Queries) DeleteWorkshopParticipant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkshopParticipant, id)
	return err
}

const deleteWorkshopParticipantsByWorkshopID = `-- name: DeleteWorkshopParticipantsByWorkshopID :exec
DELETE FROM workshop_participant WHERE workshop_id = $1
`

func (q *Queries) DeleteWorkshopParticipantsByWorkshopID(ctx context.Context, workshopID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkshopParticipantsByWorkshopID, workshopID)
	return err
}

const getInstitutionByID = `-- name: GetInstitutionByID :one
SELECT id, created_by, created_at, modified_by, modified_at, name, deleted_at, free_use_api_key_share_id, free_use_ai_quality_tier FROM institution WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstitutionByID(ctx context.Context, id uuid.UUID) (Institution, error) {
	row := q.db.QueryRowContext(ctx, getInstitutionByID, id)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.DeletedAt,
		&i.FreeUseApiKeyShareID,
		&i.FreeUseAiQualityTier,
	)
	return i, err
}

const getInstitutionMembers = `-- name: GetInstitutionMembers :many
SELECT u.id, u.name, u.email, r.role
FROM app_user u
JOIN user_role r ON u.id = r.user_id
WHERE r.institution_id = $1
  AND u.deleted_at IS NULL
  AND r.role IN ('individual', 'staff', 'head')
ORDER BY r.role, u.name
`

type GetInstitutionMembersRow struct {
	ID    uuid.UUID
	Name  string
	Email sql.NullString
	Role  sql.NullString
}

func (q *Queries) GetInstitutionMembers(ctx context.Context, institutionID uuid.NullUUID) ([]GetInstitutionMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getInstitutionMembers, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstitutionMembersRow
	for rows.Next() {
		var i GetInstitutionMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNonParticipantUserIDsByInstitution = `-- name: GetNonParticipantUserIDsByInstitution :many
SELECT DISTINCT u.id
FROM app_user u
JOIN user_role r ON u.id = r.user_id
WHERE r.institution_id = $1
  AND r.role != 'participant'
  AND u.deleted_at IS NULL
`

func (q *Queries) GetNonParticipantUserIDsByInstitution(ctx context.Context, institutionID uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getNonParticipantUserIDsByInstitution, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipantUserIDsByInstitution = `-- name: GetParticipantUserIDsByInstitution :many
SELECT DISTINCT u.id
FROM app_user u
JOIN user_role r ON u.id = r.user_id
WHERE r.institution_id = $1
  AND r.role = 'participant'
  AND u.deleted_at IS NULL
`

func (q *Queries) GetParticipantUserIDsByInstitution(ctx context.Context, institutionID uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getParticipantUserIDsByInstitution, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkshopByID = `-- name: GetWorkshopByID :one
SELECT id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at, default_api_key_share_id, ai_quality_tier, show_public_games, show_other_participants_games, design_editing_enabled, is_paused FROM workshop WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkshopByID(ctx context.Context, id uuid.UUID) (Workshop, error) {
	row := q.db.QueryRowContext(ctx, getWorkshopByID, id)
	var i Workshop
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.InstitutionID,
		&i.Active,
		&i.Public,
		&i.DeletedAt,
		&i.DefaultApiKeyShareID,
		&i.AiQualityTier,
		&i.ShowPublicGames,
		&i.ShowOtherParticipantsGames,
		&i.DesignEditingEnabled,
		&i.IsPaused,
	)
	return i, err
}

const getWorkshopParticipantByID = `-- name: GetWorkshopParticipantByID :one
SELECT id, created_by, created_at, modified_by, modified_at, workshop_id, name, access_token, active FROM workshop_participant WHERE id = $1
`

func (q *Queries) GetWorkshopParticipantByID(ctx context.Context, id uuid.UUID) (WorkshopParticipant, error) {
	row := q.db.QueryRowContext(ctx, getWorkshopParticipantByID, id)
	var i WorkshopParticipant
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.WorkshopID,
		&i.Name,
		&i.AccessToken,
		&i.Active,
	)
	return i, err
}

const hardDeleteInstitution = `-- name: HardDeleteInstitution :exec
DELETE FROM institution WHERE id = $1
`

func (q *Queries) HardDeleteInstitution(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, hardDeleteInstitution, id)
	return err
}

const hardDeleteWorkshopsByInstitution = `-- name: HardDeleteWorkshopsByInstitution :exec
DELETE FROM workshop WHERE institution_id = $1
`

func (q *Queries) HardDeleteWorkshopsByInstitution(ctx context.Context, institutionID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, hardDeleteWorkshopsByInstitution, institutionID)
	return err
}

const listInstitutions = `-- name: ListInstitutions :many
SELECT id, created_by, created_at, modified_by, modified_at, name, deleted_at, free_use_api_key_share_id, free_use_ai_quality_tier FROM institution WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListInstitutions(ctx context.Context) ([]Institution, error) {
	rows, err := q.db.QueryContext(ctx, listInstitutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Institution
	for rows.Next() {
		var i Institution
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
			&i.Name,
			&i.DeletedAt,
			&i.FreeUseApiKeyShareID,
			&i.FreeUseAiQualityTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkshops = `-- name: ListWorkshops :many
SELECT id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at, default_api_key_share_id, ai_quality_tier, show_public_games, show_other_participants_games, design_editing_enabled, is_paused FROM workshop WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListWorkshops(ctx context.Context) ([]Workshop, error) {
	rows, err := q.db.QueryContext(ctx, listWorkshops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workshop
	for rows.Next() {
		var i Workshop
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
			&i.Name,
			&i.InstitutionID,
			&i.Active,
			&i.Public,
			&i.DeletedAt,
			&i.DefaultApiKeyShareID,
			&i.AiQualityTier,
			&i.ShowPublicGames,
			&i.ShowOtherParticipantsGames,
			&i.DesignEditingEnabled,
			&i.IsPaused,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkshopsByInstitution = `-- name: ListWorkshopsByInstitution :many
SELECT id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at, default_api_key_share_id, ai_quality_tier, show_public_games, show_other_participants_games, design_editing_enabled, is_paused FROM workshop WHERE institution_id = $1 AND deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListWorkshopsByInstitution(ctx context.Context, institutionID uuid.UUID) ([]Workshop, error) {
	rows, err := q.db.QueryContext(ctx, listWorkshopsByInstitution, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workshop
	for rows.Next() {
		var i Workshop
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
			&i.Name,
			&i.InstitutionID,
			&i.Active,
			&i.Public,
			&i.DeletedAt,
			&i.DefaultApiKeyShareID,
			&i.AiQualityTier,
			&i.ShowPublicGames,
			&i.ShowOtherParticipantsGames,
			&i.DesignEditingEnabled,
			&i.IsPaused,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInstitutionFreeUseApiKeyShare = `-- name: SetInstitutionFreeUseApiKeyShare :exec
UPDATE institution
SET free_use_api_key_share_id = $2, modified_at = now()
WHERE id = $1
`

type SetInstitutionFreeUseApiKeyShareParams struct {
	ID                   uuid.UUID
	FreeUseApiKeyShareID uuid.NullUUID
}

func (q *Queries) SetInstitutionFreeUseApiKeyShare(ctx context.Context, arg SetInstitutionFreeUseApiKeyShareParams) error {
	_, err := q.db.ExecContext(ctx, setInstitutionFreeUseApiKeyShare, arg.ID, arg.FreeUseApiKeyShareID)
	return err
}

const setWorkshopDefaultApiKey = `-- name: SetWorkshopDefaultApiKey :one
UPDATE workshop SET
  modified_by = $2,
  modified_at = now(),
  default_api_key_share_id = $3
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at, default_api_key_share_id, ai_quality_tier, show_public_games, show_other_participants_games, design_editing_enabled, is_paused
`

type SetWorkshopDefaultApiKeyParams struct {
	ID                   uuid.UUID
	ModifiedBy           uuid.NullUUID
	DefaultApiKeyShareID uuid.NullUUID
}

func (q *Queries) SetWorkshopDefaultApiKey(ctx context.Context, arg SetWorkshopDefaultApiKeyParams) (Workshop, error) {
	row := q.db.QueryRowContext(ctx, setWorkshopDefaultApiKey, arg.ID, arg.ModifiedBy, arg.DefaultApiKeyShareID)
	var i Workshop
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.InstitutionID,
		&i.Active,
		&i.Public,
		&i.DeletedAt,
		&i.DefaultApiKeyShareID,
		&i.AiQualityTier,
		&i.ShowPublicGames,
		&i.ShowOtherParticipantsGames,
		&i.DesignEditingEnabled,
		&i.IsPaused,
	)
	return i, err
}

const softDeleteInstitution = `-- name: SoftDeleteInstitution :exec
UPDATE institution SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteInstitution(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteInstitution, id)
	return err
}

const updateInstitution = `-- name: UpdateInstitution :one
UPDATE institution SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  name = $6
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, name, deleted_at, free_use_api_key_share_id, free_use_ai_quality_tier
`

type UpdateInstitutionParams struct {
	ID         uuid.UUID
	CreatedBy  uuid.NullUUID
	CreatedAt  time.Time
	ModifiedBy uuid.NullUUID
	ModifiedAt time.Time
	Name       string
}

func (q *Queries) UpdateInstitution(ctx context.Context, arg UpdateInstitutionParams) (Institution, error) {
	row := q.db.QueryRowContext(ctx, updateInstitution,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
	)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.DeletedAt,
		&i.FreeUseApiKeyShareID,
		&i.FreeUseAiQualityTier,
	)
	return i, err
}

const updateInstitutionFreeUseAiQualityTier = `-- name: UpdateInstitutionFreeUseAiQualityTier :exec
UPDATE institution
SET free_use_ai_quality_tier = $2, modified_at = now()
WHERE id = $1
`

type UpdateInstitutionFreeUseAiQualityTierParams struct {
	ID                   uuid.UUID
	FreeUseAiQualityTier sql.NullString
}

func (q *Queries) UpdateInstitutionFreeUseAiQualityTier(ctx context.Context, arg UpdateInstitutionFreeUseAiQualityTierParams) error {
	_, err := q.db.ExecContext(ctx, updateInstitutionFreeUseAiQualityTier, arg.ID, arg.FreeUseAiQualityTier)
	return err
}

const updateWorkshop = `-- name: UpdateWorkshop :one
UPDATE workshop SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  name = $6,
  institution_id = $7,
  active = $8,
  public = $9,
  default_api_key_share_id = $10,
  ai_quality_tier = $11,
  show_public_games = $12,
  show_other_participants_games = $13,
  design_editing_enabled = $14,
  is_paused = $15
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at, default_api_key_share_id, ai_quality_tier, show_public_games, show_other_participants_games, design_editing_enabled, is_paused
`

type UpdateWorkshopParams struct {
	ID                         uuid.UUID
	CreatedBy                  uuid.NullUUID
	CreatedAt                  time.Time
	ModifiedBy                 uuid.NullUUID
	ModifiedAt                 time.Time
	Name                       string
	InstitutionID              uuid.UUID
	Active                     bool
	Public                     bool
	DefaultApiKeyShareID       uuid.NullUUID
	AiQualityTier              sql.NullString
	ShowPublicGames            bool
	ShowOtherParticipantsGames bool
	DesignEditingEnabled       bool
	IsPaused                   bool
}

func (q *Queries) UpdateWorkshop(ctx context.Context, arg UpdateWorkshopParams) (Workshop, error) {
	row := q.db.QueryRowContext(ctx, updateWorkshop,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
		arg.InstitutionID,
		arg.Active,
		arg.Public,
		arg.DefaultApiKeyShareID,
		arg.AiQualityTier,
		arg.ShowPublicGames,
		arg.ShowOtherParticipantsGames,
		arg.DesignEditingEnabled,
		arg.IsPaused,
	)
	var i Workshop
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.InstitutionID,
		&i.Active,
		&i.Public,
		&i.DeletedAt,
		&i.DefaultApiKeyShareID,
		&i.AiQualityTier,
		&i.ShowPublicGames,
		&i.ShowOtherParticipantsGames,
		&i.DesignEditingEnabled,
		&i.IsPaused,
	)
	return i, err
}

const updateWorkshopParticipant = `-- name: UpdateWorkshopParticipant :one
UPDATE workshop_participant SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  workshop_id = $6,
  name = $7,
  access_token = $8,
  active = $9
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, workshop_id, name, access_token, active
`

type UpdateWorkshopParticipantParams struct {
	ID          uuid.UUID
	CreatedBy   uuid.NullUUID
	CreatedAt   time.Time
	ModifiedBy  uuid.NullUUID
	ModifiedAt  time.Time
	WorkshopID  uuid.UUID
	Name        string
	AccessToken string
	Active      bool
}

func (q *Queries) UpdateWorkshopParticipant(ctx context.Context, arg UpdateWorkshopParticipantParams) (WorkshopParticipant, error) {
	row := q.db.QueryRowContext(ctx, updateWorkshopParticipant,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.WorkshopID,
		arg.Name,
		arg.AccessToken,
		arg.Active,
	)
	var i WorkshopParticipant
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.WorkshopID,
		&i.Name,
		&i.AccessToken,
		&i.Active,
	)
	return i, err
}
