// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: institution.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInstitution = `-- name: CreateInstitution :one

INSERT INTO institution (
  id, created_by,
  created_at, modified_by, modified_at,
  name
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6
)
RETURNING id, created_by, created_at, modified_by, modified_at, name, deleted_at
`

type CreateInstitutionParams struct {
	ID         uuid.UUID
	CreatedBy  uuid.NullUUID
	CreatedAt  time.Time
	ModifiedBy uuid.NullUUID
	ModifiedAt time.Time
	Name       string
}

// institution ----------------------------------------------------------
func (q *Queries) CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (Institution, error) {
	row := q.db.QueryRowContext(ctx, createInstitution,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
	)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkshop = `-- name: CreateWorkshop :one

INSERT INTO workshop (
  id, created_by,
  created_at, modified_by, modified_at,
  name, institution_id, active, public
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6, $7, $8, $9
)
RETURNING id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at
`

type CreateWorkshopParams struct {
	ID            uuid.UUID
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	ModifiedBy    uuid.NullUUID
	ModifiedAt    time.Time
	Name          string
	InstitutionID uuid.UUID
	Active        bool
	Public        bool
}

// workshop -------------------------------------------------------------
func (q *Queries) CreateWorkshop(ctx context.Context, arg CreateWorkshopParams) (Workshop, error) {
	row := q.db.QueryRowContext(ctx, createWorkshop,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
		arg.InstitutionID,
		arg.Active,
		arg.Public,
	)
	var i Workshop
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.InstitutionID,
		&i.Active,
		&i.Public,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkshopParticipant = `-- name: CreateWorkshopParticipant :one

INSERT INTO workshop_participant (
  id, created_by,
  created_at, modified_by, modified_at,
  workshop_id, name, access_token, active
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6, $7, $8, $9
)
RETURNING id, created_by, created_at, modified_by, modified_at, workshop_id, name, access_token, active
`

type CreateWorkshopParticipantParams struct {
	ID          uuid.UUID
	CreatedBy   uuid.NullUUID
	CreatedAt   time.Time
	ModifiedBy  uuid.NullUUID
	ModifiedAt  time.Time
	WorkshopID  uuid.UUID
	Name        string
	AccessToken string
	Active      bool
}

// workshop_participant -------------------------------------------------
func (q *Queries) CreateWorkshopParticipant(ctx context.Context, arg CreateWorkshopParticipantParams) (WorkshopParticipant, error) {
	row := q.db.QueryRowContext(ctx, createWorkshopParticipant,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.WorkshopID,
		arg.Name,
		arg.AccessToken,
		arg.Active,
	)
	var i WorkshopParticipant
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.WorkshopID,
		&i.Name,
		&i.AccessToken,
		&i.Active,
	)
	return i, err
}

const deleteInstitution = `-- name: DeleteInstitution :exec
UPDATE institution SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteInstitution(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInstitution, id)
	return err
}

const deleteWorkshop = `-- name: DeleteWorkshop :exec
UPDATE workshop SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteWorkshop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkshop, id)
	return err
}

const deleteWorkshopParticipant = `-- name: DeleteWorkshopParticipant :exec
DELETE FROM workshop_participant WHERE id = $1
`

func (q *Queries) DeleteWorkshopParticipant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkshopParticipant, id)
	return err
}

const getInstitutionByID = `-- name: GetInstitutionByID :one
SELECT id, created_by, created_at, modified_by, modified_at, name, deleted_at FROM institution WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstitutionByID(ctx context.Context, id uuid.UUID) (Institution, error) {
	row := q.db.QueryRowContext(ctx, getInstitutionByID, id)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}

const getInstitutionMembers = `-- name: GetInstitutionMembers :many
SELECT u.id, u.name, u.email, r.role
FROM app_user u
JOIN user_role r ON u.id = r.user_id
WHERE r.institution_id = $1
  AND u.deleted_at IS NULL
ORDER BY r.role, u.name
`

type GetInstitutionMembersRow struct {
	ID    uuid.UUID
	Name  string
	Email sql.NullString
	Role  sql.NullString
}

func (q *Queries) GetInstitutionMembers(ctx context.Context, institutionID uuid.NullUUID) ([]GetInstitutionMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getInstitutionMembers, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstitutionMembersRow
	for rows.Next() {
		var i GetInstitutionMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkshopByID = `-- name: GetWorkshopByID :one
SELECT id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at FROM workshop WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkshopByID(ctx context.Context, id uuid.UUID) (Workshop, error) {
	row := q.db.QueryRowContext(ctx, getWorkshopByID, id)
	var i Workshop
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.InstitutionID,
		&i.Active,
		&i.Public,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkshopParticipantByID = `-- name: GetWorkshopParticipantByID :one
SELECT id, created_by, created_at, modified_by, modified_at, workshop_id, name, access_token, active FROM workshop_participant WHERE id = $1
`

func (q *Queries) GetWorkshopParticipantByID(ctx context.Context, id uuid.UUID) (WorkshopParticipant, error) {
	row := q.db.QueryRowContext(ctx, getWorkshopParticipantByID, id)
	var i WorkshopParticipant
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.WorkshopID,
		&i.Name,
		&i.AccessToken,
		&i.Active,
	)
	return i, err
}

const listInstitutions = `-- name: ListInstitutions :many
SELECT id, created_by, created_at, modified_by, modified_at, name, deleted_at FROM institution WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListInstitutions(ctx context.Context) ([]Institution, error) {
	rows, err := q.db.QueryContext(ctx, listInstitutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Institution
	for rows.Next() {
		var i Institution
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
			&i.Name,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkshops = `-- name: ListWorkshops :many
SELECT id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at FROM workshop WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListWorkshops(ctx context.Context) ([]Workshop, error) {
	rows, err := q.db.QueryContext(ctx, listWorkshops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workshop
	for rows.Next() {
		var i Workshop
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
			&i.Name,
			&i.InstitutionID,
			&i.Active,
			&i.Public,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkshopsByInstitution = `-- name: ListWorkshopsByInstitution :many
SELECT id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at FROM workshop WHERE institution_id = $1 AND deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListWorkshopsByInstitution(ctx context.Context, institutionID uuid.UUID) ([]Workshop, error) {
	rows, err := q.db.QueryContext(ctx, listWorkshopsByInstitution, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workshop
	for rows.Next() {
		var i Workshop
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
			&i.Name,
			&i.InstitutionID,
			&i.Active,
			&i.Public,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstitution = `-- name: UpdateInstitution :one
UPDATE institution SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  name = $6
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, name, deleted_at
`

type UpdateInstitutionParams struct {
	ID         uuid.UUID
	CreatedBy  uuid.NullUUID
	CreatedAt  time.Time
	ModifiedBy uuid.NullUUID
	ModifiedAt time.Time
	Name       string
}

func (q *Queries) UpdateInstitution(ctx context.Context, arg UpdateInstitutionParams) (Institution, error) {
	row := q.db.QueryRowContext(ctx, updateInstitution,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
	)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkshop = `-- name: UpdateWorkshop :one
UPDATE workshop SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  name = $6,
  institution_id = $7,
  active = $8,
  public = $9
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, name, institution_id, active, public, deleted_at
`

type UpdateWorkshopParams struct {
	ID            uuid.UUID
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	ModifiedBy    uuid.NullUUID
	ModifiedAt    time.Time
	Name          string
	InstitutionID uuid.UUID
	Active        bool
	Public        bool
}

func (q *Queries) UpdateWorkshop(ctx context.Context, arg UpdateWorkshopParams) (Workshop, error) {
	row := q.db.QueryRowContext(ctx, updateWorkshop,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
		arg.InstitutionID,
		arg.Active,
		arg.Public,
	)
	var i Workshop
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.InstitutionID,
		&i.Active,
		&i.Public,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkshopParticipant = `-- name: UpdateWorkshopParticipant :one
UPDATE workshop_participant SET
  created_by = $2,
  created_at = $3,
  modified_by = $4,
  modified_at = $5,
  workshop_id = $6,
  name = $7,
  access_token = $8,
  active = $9
WHERE id = $1
RETURNING id, created_by, created_at, modified_by, modified_at, workshop_id, name, access_token, active
`

type UpdateWorkshopParticipantParams struct {
	ID          uuid.UUID
	CreatedBy   uuid.NullUUID
	CreatedAt   time.Time
	ModifiedBy  uuid.NullUUID
	ModifiedAt  time.Time
	WorkshopID  uuid.UUID
	Name        string
	AccessToken string
	Active      bool
}

func (q *Queries) UpdateWorkshopParticipant(ctx context.Context, arg UpdateWorkshopParticipantParams) (WorkshopParticipant, error) {
	row := q.db.QueryRowContext(ctx, updateWorkshopParticipant,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.WorkshopID,
		arg.Name,
		arg.AccessToken,
		arg.Active,
	)
	var i WorkshopParticipant
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.WorkshopID,
		&i.Name,
		&i.AccessToken,
		&i.Active,
	)
	return i, err
}
