// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID         uuid.UUID
	CreatedBy  uuid.NullUUID
	CreatedAt  time.Time
	ModifiedBy uuid.NullUUID
	ModifiedAt time.Time
	UserID     uuid.UUID
	Platform   string
	Key        string
}

type ApiKeyShareUser struct {
	ID                        uuid.UUID
	CreatedBy                 uuid.NullUUID
	CreatedAt                 time.Time
	ModifiedBy                uuid.NullUUID
	ModifiedAt                time.Time
	ApiKeyID                  uuid.UUID
	UserID                    uuid.UUID
	AllowPublicSponsoredPlays bool
}

type ApiKeyShareWorkshop struct {
	ID                        uuid.UUID
	CreatedBy                 uuid.NullUUID
	CreatedAt                 time.Time
	ModifiedBy                uuid.NullUUID
	ModifiedAt                time.Time
	ApiKeyID                  uuid.UUID
	WorkshopID                uuid.UUID
	AllowPublicSponsoredPlays bool
}

type AppUser struct {
	ID         uuid.UUID
	CreatedBy  uuid.NullUUID
	CreatedAt  time.Time
	ModifiedBy uuid.NullUUID
	ModifiedAt time.Time
	Name       string
	Email      sql.NullString
	DeletedAt  sql.NullTime
	Auth0ID    sql.NullString
}

type Game struct {
	ID                       uuid.UUID
	CreatedBy                uuid.NullUUID
	CreatedAt                time.Time
	ModifiedBy               uuid.NullUUID
	ModifiedAt               time.Time
	Name                     string
	Description              sql.NullString
	Icon                     []byte
	Public                   bool
	PublicSponsoredApiKeyID  uuid.NullUUID
	PrivateShareHash         sql.NullString
	PrivateSponsoredApiKeyID uuid.NullUUID
	SystemMessageScenario    string
	SystemMessageGameStart   string
	ImageStyle               string
	Css                      sql.NullString
	StatusFields             string
	FirstMessage             sql.NullString
	FirstStatus              sql.NullString
	FirstImage               []byte
}

type GameSession struct {
	ID           uuid.UUID
	CreatedBy    uuid.NullUUID
	CreatedAt    time.Time
	ModifiedBy   uuid.NullUUID
	ModifiedAt   time.Time
	GameID       uuid.UUID
	UserID       uuid.UUID
	ApiKeyID     uuid.UUID
	Model        string
	ModelSession json.RawMessage
	ImageStyle   string
	StatusFields string
}

type GameSessionMessage struct {
	ID            uuid.UUID
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	ModifiedBy    uuid.NullUUID
	ModifiedAt    time.Time
	GameSessionID uuid.UUID
	Type          string
	Message       string
	Status        sql.NullString
	ImagePrompt   sql.NullString
	Image         []byte
}

type GameTag struct {
	ID         uuid.UUID
	CreatedBy  uuid.NullUUID
	CreatedAt  time.Time
	ModifiedBy uuid.NullUUID
	ModifiedAt time.Time
	GameID     uuid.UUID
	Tag        string
}

type Institution struct {
	ID         uuid.UUID
	CreatedBy  uuid.NullUUID
	CreatedAt  time.Time
	ModifiedBy uuid.NullUUID
	ModifiedAt time.Time
	Name       string
}

type UserRole struct {
	ID            uuid.NullUUID
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	ModifiedBy    uuid.NullUUID
	ModifiedAt    time.Time
	UserID        uuid.UUID
	Role          sql.NullString
	InstitutionID uuid.NullUUID
}

type Workshop struct {
	ID            uuid.UUID
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	ModifiedBy    uuid.NullUUID
	ModifiedAt    time.Time
	Name          string
	InstitutionID uuid.UUID
	Active        bool
	Public        bool
}

type WorkshopParticipant struct {
	ID          uuid.UUID
	CreatedBy   uuid.NullUUID
	CreatedAt   time.Time
	ModifiedBy  uuid.NullUUID
	ModifiedAt  time.Time
	WorkshopID  uuid.UUID
	Name        string
	AccessToken string
	Active      bool
}
