// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSystemSettings = `-- name: GetSystemSettings :one

SELECT
  id,
  created_at,
  modified_at,
  default_ai_model
FROM system_settings
LIMIT 1
`

type GetSystemSettingsRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	ModifiedAt     time.Time
	DefaultAiModel string
}

// System Settings queries
func (q *Queries) GetSystemSettings(ctx context.Context) (GetSystemSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSystemSettings)
	var i GetSystemSettingsRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DefaultAiModel,
	)
	return i, err
}

const initSystemSettings = `-- name: InitSystemSettings :exec
INSERT INTO system_settings (id, default_ai_model)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, $1)
ON CONFLICT DO NOTHING
`

func (q *Queries) InitSystemSettings(ctx context.Context, defaultAiModel string) error {
	_, err := q.db.ExecContext(ctx, initSystemSettings, defaultAiModel)
	return err
}

const updateDefaultAiModel = `-- name: UpdateDefaultAiModel :exec
UPDATE system_settings
SET
  default_ai_model = $1,
  modified_at = now()
`

func (q *Queries) UpdateDefaultAiModel(ctx context.Context, defaultAiModel string) error {
	_, err := q.db.ExecContext(ctx, updateDefaultAiModel, defaultAiModel)
	return err
}
