// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const clearSystemSettingsFreeUseApiKey = `-- name: ClearSystemSettingsFreeUseApiKey :exec
UPDATE system_settings
SET
  free_use_api_key_id = NULL,
  modified_at = now()
WHERE free_use_api_key_id = $1
`

func (q *Queries) ClearSystemSettingsFreeUseApiKey(ctx context.Context, freeUseApiKeyID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, clearSystemSettingsFreeUseApiKey, freeUseApiKeyID)
	return err
}

const clearSystemSettingsFreeUseApiKeyByOwner = `-- name: ClearSystemSettingsFreeUseApiKeyByOwner :exec
UPDATE system_settings
SET
  free_use_api_key_id = NULL,
  modified_at = now()
WHERE free_use_api_key_id IN (
  SELECT id FROM api_key WHERE user_id = $1
)
`

func (q *Queries) ClearSystemSettingsFreeUseApiKeyByOwner(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearSystemSettingsFreeUseApiKeyByOwner, userID)
	return err
}

const getSystemSettings = `-- name: GetSystemSettings :one

SELECT
  id,
  created_at,
  modified_at,
  default_ai_quality_tier,
  free_use_ai_quality_tier,
  free_use_api_key_id
FROM system_settings
LIMIT 1
`

type GetSystemSettingsRow struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	ModifiedAt           time.Time
	DefaultAiQualityTier string
	FreeUseAiQualityTier sql.NullString
	FreeUseApiKeyID      uuid.NullUUID
}

// System Settings queries
func (q *Queries) GetSystemSettings(ctx context.Context) (GetSystemSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSystemSettings)
	var i GetSystemSettingsRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DefaultAiQualityTier,
		&i.FreeUseAiQualityTier,
		&i.FreeUseApiKeyID,
	)
	return i, err
}

const initSystemSettings = `-- name: InitSystemSettings :exec
INSERT INTO system_settings (id, default_ai_quality_tier)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, $1)
ON CONFLICT DO NOTHING
`

func (q *Queries) InitSystemSettings(ctx context.Context, defaultAiQualityTier string) error {
	_, err := q.db.ExecContext(ctx, initSystemSettings, defaultAiQualityTier)
	return err
}

const updateDefaultAiQualityTier = `-- name: UpdateDefaultAiQualityTier :exec
UPDATE system_settings
SET
  default_ai_quality_tier = $1,
  modified_at = now()
`

func (q *Queries) UpdateDefaultAiQualityTier(ctx context.Context, defaultAiQualityTier string) error {
	_, err := q.db.ExecContext(ctx, updateDefaultAiQualityTier, defaultAiQualityTier)
	return err
}

const updateFreeUseAiQualityTier = `-- name: UpdateFreeUseAiQualityTier :exec
UPDATE system_settings
SET
  free_use_ai_quality_tier = $1,
  modified_at = now()
`

func (q *Queries) UpdateFreeUseAiQualityTier(ctx context.Context, freeUseAiQualityTier sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updateFreeUseAiQualityTier, freeUseAiQualityTier)
	return err
}

const updateSystemSettingsFreeUseApiKey = `-- name: UpdateSystemSettingsFreeUseApiKey :exec
UPDATE system_settings
SET
  free_use_api_key_id = $1,
  modified_at = now()
`

func (q *Queries) UpdateSystemSettingsFreeUseApiKey(ctx context.Context, freeUseApiKeyID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, updateSystemSettingsFreeUseApiKey, freeUseApiKeyID)
	return err
}
