// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

INSERT INTO app_user (id, name, email, auth0_id)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id
`

type CreateUserParams struct {
	Name    string
	Email   sql.NullString
	Auth0ID sql.NullString
}

// app_user -------------------------------------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.Auth0ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUserRole = `-- name: CreateUserRole :one
INSERT INTO user_role (id, user_id, role, institution_id)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id
`

type CreateUserRoleParams struct {
	UserID        uuid.UUID
	Role          sql.NullString
	InstitutionID uuid.NullUUID
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (uuid.NullUUID, error) {
	row := q.db.QueryRowContext(ctx, createUserRole, arg.UserID, arg.Role, arg.InstitutionID)
	var id uuid.NullUUID
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE app_user
SET
  deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec

DELETE FROM user_role WHERE user_id = $1
`

// user_role -------------------------------------------------------------
func (q *Queries) DeleteUserRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserRoles, userID)
	return err
}

const getUserApiKeys = `-- name: GetUserApiKeys :many
SELECT
  id,
  created_by,
  created_at,
  modified_by,
  modified_at,
  user_id,
  platform,
  key
FROM api_key
WHERE user_id = $1
`

func (q *Queries) GetUserApiKeys(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, getUserApiKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
			&i.UserID,
			&i.Platform,
			&i.Key,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_by, created_at, modified_by, modified_at, name, email, deleted_at, auth0_id FROM app_user WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.Email,
		&i.DeletedAt,
		&i.Auth0ID,
	)
	return i, err
}

const getUserDetailsByID = `-- name: GetUserDetailsByID :one
SELECT
  u.id,
  u.created_by,
  u.created_at,
  u.modified_by,
  u.modified_at,
  u.name,
  u.email,
  u.deleted_at,
  u.auth0_id,
  r.id           AS role_id,
  r.role         AS role,
  r.institution_id,
  i.name         AS institution_name
FROM app_user u
LEFT JOIN LATERAL (
  SELECT ur.id, ur.created_by, ur.created_at, ur.modified_by, ur.modified_at, ur.user_id, ur.role, ur.institution_id
  FROM user_role ur
  WHERE ur.user_id = u.id
  ORDER BY ur.created_at DESC
  LIMIT 1
) r ON TRUE
LEFT JOIN institution i
  ON i.id = r.institution_id
WHERE u.id = $1
`

type GetUserDetailsByIDRow struct {
	ID              uuid.UUID
	CreatedBy       uuid.NullUUID
	CreatedAt       time.Time
	ModifiedBy      uuid.NullUUID
	ModifiedAt      time.Time
	Name            string
	Email           sql.NullString
	DeletedAt       sql.NullTime
	Auth0ID         sql.NullString
	RoleID          uuid.NullUUID
	Role            sql.NullString
	InstitutionID   uuid.NullUUID
	InstitutionName sql.NullString
}

func (q *Queries) GetUserDetailsByID(ctx context.Context, id uuid.UUID) (GetUserDetailsByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserDetailsByID, id)
	var i GetUserDetailsByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
		&i.Name,
		&i.Email,
		&i.DeletedAt,
		&i.Auth0ID,
		&i.RoleID,
		&i.Role,
		&i.InstitutionID,
		&i.InstitutionName,
	)
	return i, err
}

const getUserIDByAuth0ID = `-- name: GetUserIDByAuth0ID :one
SELECT id FROM app_user WHERE auth0_id = $1
`

func (q *Queries) GetUserIDByAuth0ID(ctx context.Context, auth0ID sql.NullString) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByAuth0ID, auth0ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE app_user SET
  name = $2,
  email = $3,
  modified_at = now()
WHERE id = $1
`

type UpdateUserParams struct {
	ID    uuid.UUID
	Name  string
	Email sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.ID, arg.Name, arg.Email)
	return err
}
