// Command gen-protocol writes the TypeScript view of the engine's wire
// protocol from the Go types that define it.
//
// The monolith generates its client from OpenAPI, which cannot describe frames
// on a WebSocket — and the session protocol is a WebSocket. So the contract
// that actually matters is the event message, and this keeps the Go and
// TypeScript sides of it from drifting.
//
//	go run ./cmd/gen-protocol            # write web/src/protocol.ts
//	go run ./cmd/gen-protocol -check     # fail if it is stale
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	"engine"
)

const output = "web/src/protocol.ts"

func main() {
	check := flag.Bool("check", false, "fail if the generated file is out of date")
	flag.Parse()

	want := generate()

	if !*check {
		if err := os.WriteFile(output, want, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Println("wrote", output)
		return
	}

	got, err := os.ReadFile(output)
	if err != nil || !bytes.Equal(got, want) {
		fmt.Fprintf(os.Stderr, "%s is out of date; run: go run ./cmd/gen-protocol\n", output)
		os.Exit(1)
	}
}

func generate() []byte {
	var b strings.Builder
	b.WriteString("// Generated by cmd/gen-protocol. Do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// The engine's wire protocol, from the Go types that define it.\n\n")

	b.WriteString("/**\n")
	b.WriteString(" * Stream names are not an open vocabulary: each one is an output block a\n")
	b.WriteString(" * genre wired, so this union is the client-side mirror of the graph.\n")
	b.WriteString(" */\n")
	b.WriteString("export type StreamName =\n")
	for _, name := range engine.StreamNames() {
		fmt.Fprintf(&b, "  | %q\n", name)
	}
	b.WriteString("  ;\n\n")

	b.WriteString("/** One item on the session-scoped event stream. */\n")
	b.WriteString("export interface SessionEvent {\n")
	for _, field := range tsFields(reflect.TypeOf(engine.Event{})) {
		fmt.Fprintf(&b, "  readonly %s: %s;\n", field.name, field.tsType)
	}
	b.WriteString("}\n\n")

	b.WriteString("export function isSessionEvent(value: unknown): value is SessionEvent {\n")
	b.WriteString("  if (typeof value !== \"object\" || value === null) return false;\n")
	b.WriteString("  const candidate = value as Partial<SessionEvent>;\n")
	b.WriteString("  return (\n")
	fields := tsFields(reflect.TypeOf(engine.Event{}))
	for i, field := range fields {
		sep := " &&"
		if i == len(fields)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, "    typeof candidate.%s === %q%s\n", field.name, jsTypeof(field.tsType), sep)
	}
	b.WriteString("  );\n")
	b.WriteString("}\n")

	return []byte(b.String())
}

type tsField struct {
	name   string
	tsType string
}

func tsFields(t reflect.Type) []tsField {
	var out []tsField
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		name := f.Name
		if tag := f.Tag.Get("json"); tag != "" {
			if parts := strings.Split(tag, ","); parts[0] != "" && parts[0] != "-" {
				name = parts[0]
			}
		}
		ts := tsType(f.Type)
		// The stream is the one field whose values are closed, so it carries
		// the union rather than a bare string.
		if name == "Stream" {
			ts = "StreamName"
		}
		out = append(out, tsField{name: name, tsType: ts})
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

func tsType(t reflect.Type) string {
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	default:
		return "unknown"
	}
}

func jsTypeof(ts string) string {
	switch ts {
	case "boolean", "number":
		return ts
	default:
		// Including StreamName: a union of string literals is a string at
		// runtime, which is all a guard can check.
		return "string"
	}
}
