/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as MyOrganizationIndexRouteImport } from './routes/my-organization/index'
import { Route as MyGamesIndexRouteImport } from './routes/my-games/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as CreationsIndexRouteImport } from './routes/creations/index'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as MyOrganizationWorkshopsRouteImport } from './routes/my-organization/workshops'
import { Route as MyOrganizationApiKeysRouteImport } from './routes/my-organization/api-keys'
import { Route as MyGamesCreateRouteImport } from './routes/my-games/create'
import { Route as MyGamesGameIdRouteImport } from './routes/my-games/$gameId'
import { Route as CreationsCreateRouteImport } from './routes/creations/create'
import { Route as CreationsGameIdRouteImport } from './routes/creations/$gameId'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as GamesGameIdPlayRouteImport } from './routes/games/$gameId/play'
import { Route as AuthLogoutAuth0CallbackRouteImport } from './routes/auth/logout/auth0/callback'
import { Route as AuthLoginAuth0CallbackRouteImport } from './routes/auth/login/auth0/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrganizationIndexRoute = MyOrganizationIndexRouteImport.update({
  id: '/my-organization/',
  path: '/my-organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGamesIndexRoute = MyGamesIndexRouteImport.update({
  id: '/my-games/',
  path: '/my-games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsIndexRoute = CreationsIndexRouteImport.update({
  id: '/creations/',
  path: '/creations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrganizationWorkshopsRoute = MyOrganizationWorkshopsRouteImport.update({
  id: '/my-organization/workshops',
  path: '/my-organization/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrganizationApiKeysRoute = MyOrganizationApiKeysRouteImport.update({
  id: '/my-organization/api-keys',
  path: '/my-organization/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGamesCreateRoute = MyGamesCreateRouteImport.update({
  id: '/my-games/create',
  path: '/my-games/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGamesGameIdRoute = MyGamesGameIdRouteImport.update({
  id: '/my-games/$gameId',
  path: '/my-games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsCreateRoute = CreationsCreateRouteImport.update({
  id: '/creations/create',
  path: '/creations/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsGameIdRoute = CreationsGameIdRouteImport.update({
  id: '/creations/$gameId',
  path: '/creations/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/admin/organizations/',
  path: '/admin/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdPlayRoute = GamesGameIdPlayRouteImport.update({
  id: '/games/$gameId/play',
  path: '/games/$gameId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutAuth0CallbackRoute = AuthLogoutAuth0CallbackRouteImport.update({
  id: '/auth/logout/auth0/callback',
  path: '/auth/logout/auth0/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginAuth0CallbackRoute = AuthLoginAuth0CallbackRouteImport.update({
  id: '/auth/login/auth0/callback',
  path: '/auth/login/auth0/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/creations/$gameId': typeof CreationsGameIdRoute
  '/creations/create': typeof CreationsCreateRoute
  '/my-games/$gameId': typeof MyGamesGameIdRoute
  '/my-games/create': typeof MyGamesCreateRoute
  '/my-organization/api-keys': typeof MyOrganizationApiKeysRoute
  '/my-organization/workshops': typeof MyOrganizationWorkshopsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/creations': typeof CreationsIndexRoute
  '/games': typeof GamesIndexRoute
  '/my-games': typeof MyGamesIndexRoute
  '/my-organization': typeof MyOrganizationIndexRoute
  '/play': typeof PlayIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/login/auth0/callback': typeof AuthLoginAuth0CallbackRoute
  '/auth/logout/auth0/callback': typeof AuthLogoutAuth0CallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/creations/$gameId': typeof CreationsGameIdRoute
  '/creations/create': typeof CreationsCreateRoute
  '/my-games/$gameId': typeof MyGamesGameIdRoute
  '/my-games/create': typeof MyGamesCreateRoute
  '/my-organization/api-keys': typeof MyOrganizationApiKeysRoute
  '/my-organization/workshops': typeof MyOrganizationWorkshopsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/creations': typeof CreationsIndexRoute
  '/games': typeof GamesIndexRoute
  '/my-games': typeof MyGamesIndexRoute
  '/my-organization': typeof MyOrganizationIndexRoute
  '/play': typeof PlayIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/login/auth0/callback': typeof AuthLoginAuth0CallbackRoute
  '/auth/logout/auth0/callback': typeof AuthLogoutAuth0CallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/creations/$gameId': typeof CreationsGameIdRoute
  '/creations/create': typeof CreationsCreateRoute
  '/my-games/$gameId': typeof MyGamesGameIdRoute
  '/my-games/create': typeof MyGamesCreateRoute
  '/my-organization/api-keys': typeof MyOrganizationApiKeysRoute
  '/my-organization/workshops': typeof MyOrganizationWorkshopsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/creations/': typeof CreationsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/my-games/': typeof MyGamesIndexRoute
  '/my-organization/': typeof MyOrganizationIndexRoute
  '/play/': typeof PlayIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/login/auth0/callback': typeof AuthLoginAuth0CallbackRoute
  '/auth/logout/auth0/callback': typeof AuthLogoutAuth0CallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/creations/$gameId'
    | '/creations/create'
    | '/my-games/$gameId'
    | '/my-games/create'
    | '/my-organization/api-keys'
    | '/my-organization/workshops'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/creations'
    | '/games'
    | '/my-games'
    | '/my-organization'
    | '/play'
    | '/sessions'
    | '/games/$gameId/play'
    | '/admin/organizations'
    | '/admin/users'
    | '/auth/login'
    | '/auth/login/auth0/callback'
    | '/auth/logout/auth0/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/creations/$gameId'
    | '/creations/create'
    | '/my-games/$gameId'
    | '/my-games/create'
    | '/my-organization/api-keys'
    | '/my-organization/workshops'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/creations'
    | '/games'
    | '/my-games'
    | '/my-organization'
    | '/play'
    | '/sessions'
    | '/games/$gameId/play'
    | '/admin/organizations'
    | '/admin/users'
    | '/auth/login'
    | '/auth/login/auth0/callback'
    | '/auth/logout/auth0/callback'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/creations/$gameId'
    | '/creations/create'
    | '/my-games/$gameId'
    | '/my-games/create'
    | '/my-organization/api-keys'
    | '/my-organization/workshops'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/creations/'
    | '/games/'
    | '/my-games/'
    | '/my-organization/'
    | '/play/'
    | '/sessions/'
    | '/games/$gameId/play'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/auth/login/'
    | '/auth/login/auth0/callback'
    | '/auth/logout/auth0/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  CreationsGameIdRoute: typeof CreationsGameIdRoute
  CreationsCreateRoute: typeof CreationsCreateRoute
  MyGamesGameIdRoute: typeof MyGamesGameIdRoute
  MyGamesCreateRoute: typeof MyGamesCreateRoute
  MyOrganizationApiKeysRoute: typeof MyOrganizationApiKeysRoute
  MyOrganizationWorkshopsRoute: typeof MyOrganizationWorkshopsRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  CreationsIndexRoute: typeof CreationsIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  MyGamesIndexRoute: typeof MyGamesIndexRoute
  MyOrganizationIndexRoute: typeof MyOrganizationIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  GamesGameIdPlayRoute: typeof GamesGameIdPlayRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthLoginAuth0CallbackRoute: typeof AuthLoginAuth0CallbackRoute
  AuthLogoutAuth0CallbackRoute: typeof AuthLogoutAuth0CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-organization/': {
      id: '/my-organization/'
      path: '/my-organization'
      fullPath: '/my-organization'
      preLoaderRoute: typeof MyOrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-games/': {
      id: '/my-games/'
      path: '/my-games'
      fullPath: '/my-games'
      preLoaderRoute: typeof MyGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations/': {
      id: '/creations/'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-organization/workshops': {
      id: '/my-organization/workshops'
      path: '/my-organization/workshops'
      fullPath: '/my-organization/workshops'
      preLoaderRoute: typeof MyOrganizationWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-organization/api-keys': {
      id: '/my-organization/api-keys'
      path: '/my-organization/api-keys'
      fullPath: '/my-organization/api-keys'
      preLoaderRoute: typeof MyOrganizationApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-games/create': {
      id: '/my-games/create'
      path: '/my-games/create'
      fullPath: '/my-games/create'
      preLoaderRoute: typeof MyGamesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-games/$gameId': {
      id: '/my-games/$gameId'
      path: '/my-games/$gameId'
      fullPath: '/my-games/$gameId'
      preLoaderRoute: typeof MyGamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations/create': {
      id: '/creations/create'
      path: '/creations/create'
      fullPath: '/creations/create'
      preLoaderRoute: typeof CreationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations/$gameId': {
      id: '/creations/$gameId'
      path: '/creations/$gameId'
      fullPath: '/creations/$gameId'
      preLoaderRoute: typeof CreationsGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/play': {
      id: '/games/$gameId/play'
      path: '/games/$gameId/play'
      fullPath: '/games/$gameId/play'
      preLoaderRoute: typeof GamesGameIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout/auth0/callback': {
      id: '/auth/logout/auth0/callback'
      path: '/auth/logout/auth0/callback'
      fullPath: '/auth/logout/auth0/callback'
      preLoaderRoute: typeof AuthLogoutAuth0CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/auth0/callback': {
      id: '/auth/login/auth0/callback'
      path: '/auth/login/auth0/callback'
      fullPath: '/auth/login/auth0/callback'
      preLoaderRoute: typeof AuthLoginAuth0CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  CreationsGameIdRoute: CreationsGameIdRoute,
  CreationsCreateRoute: CreationsCreateRoute,
  MyGamesGameIdRoute: MyGamesGameIdRoute,
  MyGamesCreateRoute: MyGamesCreateRoute,
  MyOrganizationApiKeysRoute: MyOrganizationApiKeysRoute,
  MyOrganizationWorkshopsRoute: MyOrganizationWorkshopsRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  CreationsIndexRoute: CreationsIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  MyGamesIndexRoute: MyGamesIndexRoute,
  MyOrganizationIndexRoute: MyOrganizationIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  GamesGameIdPlayRoute: GamesGameIdPlayRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthLoginAuth0CallbackRoute: AuthLoginAuth0CallbackRoute,
  AuthLogoutAuth0CallbackRoute: AuthLogoutAuth0CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
